In [1]:
import pandas as pd

In [2]:
contents = pd.read_parquet("data/original/playlist_contents.parquet")
track_metadata = pd.read_parquet("data/original/track_metadata.parquet")

In [3]:
track_uri_mapping = track_metadata[["track_uri"]].reset_index(drop=True).reset_index().rename(columns={'index': 'new_track_uri'})
track_uri_mapping.head()

   new_track_uri  track_uri
0              0          0
1              1          1
2              2          2
3              3          3
4              4          4

In [4]:
artist_uri_mapping = track_metadata[["artist_uri"]].drop_duplicates().reset_index(drop=True).reset_index().rename(columns={'index': 'new_artist_uri'})
artist_uri_mapping.head()

   new_artist_uri  artist_uri
0               0           0
1               1           1
2               2           2
3               3           3
4               4           4

In [5]:
album_uri_mapping = track_metadata[["album_uri"]].drop_duplicates().reset_index(drop=True).reset_index().rename(columns={'index': 'new_album_uri'})
album_uri_mapping.head()

   new_album_uri  album_uri
0              0          0
1              1          1
2              2          2
3              3          3
4              4          4

In [6]:
contents = contents.merge(track_uri_mapping, on="track_uri")
contents["track_uri"] = contents["new_track_uri"]
contents = contents.drop(columns=["new_track_uri"])
contents

             pid  track_uri  position
0              0          0         0
1              0          1         1
2              0          2         2
3              0          3         3
4              0          4         4
...          ...        ...       ...
66346423  999999      72432       105
66346424  999999     288294       106
66346425  999999     141054       107
66346426  999999     141039       108
66346427  999999      72395       109

[66346428 rows x 3 columns]

In [7]:
track_metadata = track_metadata.merge(track_uri_mapping, on="track_uri")
track_metadata = track_metadata.merge(artist_uri_mapping, on="artist_uri")
track_metadata = track_metadata.merge(album_uri_mapping, on="album_uri")
track_metadata["track_uri"] = track_metadata["new_track_uri"]
track_metadata["artist_uri"] = track_metadata["new_artist_uri"]
track_metadata["album_uri"] = track_metadata["new_album_uri"]
track_metadata = track_metadata.drop(columns=["new_track_uri", "new_artist_uri", "new_album_uri"])
track_metadata

,track_uri,album_uri,artist_uri,track_name,album_name,artist_name,duration_ms
0,0,0,0,Lose Control (feat. Ciara & Fat Man Scoop),The Cookbook,Missy Elliott,226863
1,1,1,1,Toxic,In The Zone,Britney Spears,198800
2,2,2,2,Crazy In Love,Dangerously In Love (Alben für die Ewigkeit),Beyoncé,235933
3,3,3,3,Rock Your Body,Justified,Justin Timberlake,267266
4,4,4,4,It Wasn't Me,Hot Shot,Shaggy,227600
...,...,...,...,...,...,...,...
2262287,2262287,229637,93486,Forevermind - Pax217 Album Version,Two Seventeen,Pax217,206400
2262288,2262288,229637,93486,Shalom - Pax217 Album Version,Two Seventeen,Pax217,268266
2262289,2262289,229637,93486,Free To Be - Pax217 Album Version,Two Seventeen,Pax217,334280
2262290,2262290,229637,93486,Skwid - Pax217 Album Version,Two Seventeen,Pax217,240453
2262291,2262291,734683,295859,Running Thin,The Straw Theory,Straw Theory,341933

In [8]:
track_metadata["track_uri"] = track_metadata["track_uri"].astype("uint32")
track_metadata["artist_uri"] = track_metadata["artist_uri"].astype("uint32")
track_metadata["album_uri"] = track_metadata["album_uri"].astype("uint32")

contents["track_uri"] = contents["track_uri"].astype("uint32")

In [9]:
contents.to_parquet("data/original/playlist_contents.parquet")
track_metadata.to_parquet("data/original/track_metadata.parquet")

In [10]:
track_uri_mapping.to_parquet("data/uri_mappings/track_uri_mappings.parquet")
artist_uri_mapping.to_parquet("data/uri_mappings/artist_uri_mappings.parquet")
album_uri_mapping.to_parquet("data/uri_mappings/album_uri_mappings.parquet")